create pages with simple text
Khanhnqps10920/t-dashboard pull request #12
Opened 2022-12-28 12:01 UTC by MQuang1609

2022-12-28 12:02 UTC, MQuang1609 commented
![image](https://user-images.githubusercontent.com/114815034/209809162-864f68b0-7b61-4950-a565-b24e370d1e50.png)

2022-12-28 12:11 UTC, ntc2019 requested changes

2022-12-28 12:11 UTC, ntc2019 commented on src/components/DashboardLayout/Sidebar/data/navlink-data.tsx
>      icon_active: JSX.Element,
Remove icon_active if not implement it but using class instead.

2022-12-28 12:13 UTC, ntc2019 commented on src/components/DashboardLayout/Sidebar/data/navlink-data.tsx
> +        text: 'Oder',
Typo. Orders not Oder. Should be plural in general case.

2022-12-28 15:12 UTC, Khanhnqps10920 commented
Conflict, sử dụng antdesign icon thay vì react icon @MQuang1609

2022-12-30 18:21 UTC, Khanhnqps10920 commented on src/utils/constant.tsx
> +  ODER: '/oder',
orders em ơi

2022-12-30 18:21 UTC, Khanhnqps10920 commented on src/components/DashboardLayout/Sidebar/pages/Oder/index.tsx
> +export const OderPage = () => {
đặt tên là OrdersPage

2022-12-31 10:00 UTC, ntc2019 approved these changes

2023-01-01 06:15 UTC, merged